apiVersion: v1
kind: Service
metadata:
  name: shopflow-api-service
  namespace: shopflow-production
  labels:
    app: shopflow-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: shopflow-api
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: shopflow-production
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: shopflow-production
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopflow-ingress
  namespace: shopflow-production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - api.shopflow.com
    secretName: shopflow-tls-secret
  rules:
  - host: api.shopflow.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopflow-api-service
            port:
              number: 80
