apiVersion: v1
kind: ConfigMap
metadata:
  name: shopflow-config
  namespace: shopflow-production
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Kestrel": {
        "Endpoints": {
          "Http": {
            "Url": "http://0.0.0.0:8080"
          }
        }
      },
      "HealthChecks": {
        "UI": {
          "HealthChecksUri": "/health",
          "UIPath": "/health-ui"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: shopflow-secrets
  namespace: shopflow-production
type: Opaque
stringData:
  database-connection-string: "Host=postgres-service;Database=shopflow_prod;Username=shopflow_user;Password=your_secure_password_here"
  redis-connection-string: "redis-service:6379"
  jwt-secret: "your_jwt_secret_key_here_make_it_very_long_and_secure"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: shopflow-production
type: Opaque
stringData:
  username: "shopflow_user"
  password: "your_secure_password_here"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: shopflow-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: shopflow-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
