global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ShopFlow API
  - job_name: 'shopflow-api'
    static_configs:
      - targets: ['shopflow-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # PostgreSQL metrics (if pg_exporter is configured)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics (if redis_exporter is configured)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Docker daemon metrics (if enabled)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  # Application-specific metrics
  - job_name: 'shopflow-custom-metrics'
    static_configs:
      - targets: ['shopflow-api:8080']
    metrics_path: '/metrics/custom'
    scrape_interval: 30s
